-- Seed initial iBob proposals for the supervised proposal queue.
-- These rows are dry-run/supervised placeholders; no external ad account is modified.

insert into public.proposals (
  id,
  client_id,
  title,
  channel,
  type,
  reasoning,
  expected_impact,
  status,
  risk_level,
  rule_validator_passed,
  rule_validator_notes,
  created_at,
  budget_delta_brl,
  agent_version,
  prompt_version,
  metadata
)
values
  (
    'a2000000-0000-4000-8000-000000000001',
    'client-ibob',
    'Aumentar budget Google Search - Marca',
    'google_ads',
    'budget_increase',
    'ROAS da campanha de Marca esta em 6.8x nos ultimos 7 dias, acima da meta de 4.5x. O budget esgota as 14h diariamente, deixando impressoes na mesa.',
    '+R$ 280/dia de gasto; projecao de +42 conversoes/semana com ROAS mantido acima de 5x.',
    'pending',
    'low',
    true,
    null,
    now() - interval '4 hours',
    280,
    '0.1.0',
    'v1.0',
    '{"source":"initial_seed","mode":"supervised_dry_run"}'::jsonb
  ),
  (
    'a2000000-0000-4000-8000-000000000002',
    'client-ibob',
    'Reduzir bid max CPA - Campanha Frio',
    'google_ads',
    'bid_adjustment',
    'Campanha Publico Frio com CPA atual de R$ 187; meta e R$ 140. Bid maximo de R$ 95 esta gerando lances acima da eficiencia esperada.',
    'Reducao estimada de 15-20% no CPA; possivel queda de 10% no volume de conversoes no curto prazo.',
    'pending',
    'medium',
    true,
    'Volume abaixo do limiar minimo de 30 conversoes/semana. Ajuste pode impactar o aprendizado da campanha.',
    now() - interval '3 hours 50 minutes',
    null,
    '0.1.0',
    'v1.0',
    '{"source":"initial_seed","mode":"supervised_dry_run"}'::jsonb
  ),
  (
    'a2000000-0000-4000-8000-000000000003',
    'client-ibob',
    'Pausar anuncio baixo desempenho - Meta Reach',
    'meta_ads',
    'campaign_pause',
    'Anuncio Video_v3_Maio com CTR de 0.4% vs media de 1.2% no adset. CPM 34% acima dos demais. Sem conversoes em 8 dias.',
    'Redistribuicao de R$ 90/dia para os anuncios de melhor desempenho no mesmo adset.',
    'approved',
    'low',
    true,
    null,
    now() - interval '1 day 2 hours',
    null,
    '0.1.0',
    'v1.0',
    '{"source":"initial_seed","mode":"supervised_dry_run"}'::jsonb
  ),
  (
    'a2000000-0000-4000-8000-000000000004',
    'client-ibob',
    'Expandir audiencia Lookalike 3% - Meta',
    'meta_ads',
    'audience_expansion',
    'Lookalike 1% saturando com frequencia 4.2 apos 14 dias. Testar 3% pode ampliar alcance e reduzir frequencia.',
    'Ampliacao de cerca de 180k usuarios. Possivel queda de 10-15% na taxa de conversao durante o periodo de aprendizado.',
    'rejected',
    'medium',
    false,
    'Meta Ads com dados desatualizados (>2h). Nao e possivel validar a performance atual do adset de forma confiavel.',
    now() - interval '1 day',
    null,
    '0.1.0',
    'v1.0',
    '{"source":"initial_seed","mode":"supervised_dry_run"}'::jsonb
  ),
  (
    'a2000000-0000-4000-8000-000000000005',
    'client-ibob',
    'Rotacao de criativos Google Display',
    'google_ads',
    'creative_rotation',
    'Criativo Banner_B_Abril com CTR 2.1x maior que Banner_A_Abril apos 10k impressoes. Aumentar peso do B.',
    'Estimativa de +0.3% no CTR geral da campanha Display, sem impacto em gasto.',
    'executed',
    'low',
    true,
    null,
    now() - interval '2 days',
    null,
    '0.1.0',
    'v1.0',
    '{"source":"initial_seed","mode":"supervised_dry_run"}'::jsonb
  )
on conflict (id) do update
set title = excluded.title,
    channel = excluded.channel,
    type = excluded.type,
    reasoning = excluded.reasoning,
    expected_impact = excluded.expected_impact,
    status = excluded.status,
    risk_level = excluded.risk_level,
    rule_validator_passed = excluded.rule_validator_passed,
    rule_validator_notes = excluded.rule_validator_notes,
    created_at = excluded.created_at,
    budget_delta_brl = excluded.budget_delta_brl,
    agent_version = excluded.agent_version,
    prompt_version = excluded.prompt_version,
    metadata = excluded.metadata;
